### ISSUE TITLE
Intel API get_all_file_report_pages seems to be broken

### ISSUE THREAD

**Issue by keithjjones** [blacktop/virustotal-api#24] opened 2018-03-08 19:44 UTC
This is the exception I keep getting.  My search string is 'type:"peexe"' in this example:

```
  File "/usr/local/anaconda3/envs/Python3/lib/python3.5/site-packages/virus_total_apis/api.py", line 909, in get_all_file_report_pages
    next_page, response = self.get_hashes_from_search(self, query)
  File "/usr/local/anaconda3/envs/Python3/lib/python3.5/site-packages/virus_total_apis/api.py", line 863, in get_hashes_from_search
    return response.json().get('next_page'), response
  File "/usr/local/anaconda3/envs/Python3/lib/python3.5/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/anaconda3/envs/Python3/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/anaconda3/envs/Python3/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/anaconda3/envs/Python3/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 1 (char 4)
```

I'm on a mac, running Python3.  My call to it is pretty simple:

```
    print(args.Query)
    f = intel_api.get_all_file_report_pages(args.Query)
    print(f)
```

**Comment by blacktop** [comment] 2018-03-09 04:06
@leadZERO is this something in the code we worked on?

**Comment by leadZERO** [comment] 2018-03-09 13:44
Hmmm, I don't believe so. Although the error is related to the same problem, it looks like VT might have changed the API again. If you use an invalid API key it sends back an HTTP 200 response code and tries to redirect you to a login page. 

@keithjjones can you try going to this page in your webbrowser, replace APIKEY with your VTI API key: https://www.virustotal.com/intelligence/search/programmatic/?apikey=APIKEY&query=type:peexe 

If you are redirected to a login page, something is likely wrong with your VirusTotal Intelligence api key. You are on a paid plan correct?

This query worked with my API key:
```
from virus_total_apis import IntelApi
ia = IntelApi('HIDDEN')
f = ia.get_all_file_report_pages('type:peexe AND size:250-')
len(f['results'])
Out[7]: 13
```

But using a bogus key resulted in the json error
```
ia = IntelApi('asdfasdf')
f = ia.get_all_file_report_pages('type:peexe AND size:250-')
Traceback (most recent call last):
  File "/Users/leadzero/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-6779cec6844e>", line 1, in <module>
    f = ia.get_all_file_report_pages('type:peexe AND size:250-')
  File "/Users/leadzero/github/gh.virustotal-api/virus_total_apis/api.py", line 868, in get_all_file_report_pages
    r = self.get_hashes_from_search(query)
  File "/Users/leadzero/github/gh.virustotal-api/virus_total_apis/api.py", line 831, in get_hashes_from_search
    return _return_response_and_status_code(response)
  File "/Users/leadzero/github/gh.virustotal-api/virus_total_apis/api.py", line 963, in _return_response_and_status_code
    return dict(results=response.json() if json_results else response.content, response_code=response.status_code)
  File "/Users/leadzero/anaconda/lib/python3.6/site-packages/requests/models.py", line 885, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/leadzero/anaconda/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/leadzero/anaconda/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/leadzero/anaconda/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 1 (char 4)
```

Looking into the response for a raw query I see the following:
```
import requests
r = requests.get('https://www.virustotal.com/intelligence/search/programmatic/?apikey=APIKEY&query=type:peexe')
r.status_code
Out[12]: 200
r.url
Out[13]: 'https://www.virustotal.com/en/signin?next=/intelligence/search/programmatic/%3Fapikey%3DAPIKEY%26query%3Dtype%3Apeexe'
r.content[:100]
Out[14]: b'\n\n\n\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1'
```

VT used to return a 403 for privilege issues:
```    
elif response.status_code == 403:
        return dict(
            error='You tried to perform calls to functions for which you require a Private API key.',
response_code=response.status_code)
```

I'll see if I can handle this in the newer return standardization mentioned in #23

**Comment by keithjjones** [comment] 2018-03-09 14:09
Going to the link directly works fine.  I tried the code you said that worked, and it didn't work for me:

```
>>> f = ia.get_all_file_report_pages('type:peexe AND size:250-')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/Python3/lib/python3.5/site-packages/virus_total_apis/api.py", line 909, in get_all_file_report_pages
    next_page, response = self.get_hashes_from_search(self, query)
  File "/usr/local/anaconda3/envs/Python3/lib/python3.5/site-packages/virus_total_apis/api.py", line 863, in get_hashes_from_search
    return response.json().get('next_page'), response
  File "/usr/local/anaconda3/envs/Python3/lib/python3.5/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/anaconda3/envs/Python3/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/anaconda3/envs/Python3/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/anaconda3/envs/Python3/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 1 (char 4)
```

**Comment by keithjjones** [comment] 2018-03-09 14:15
And, everything else in IntelAPI seems to work fine for me.  I'm using the other functions.  It just seems to be this one that is causing problems.  I looked over the function but did not see anything that jumps out at me.

**Comment by keithjjones** [comment] 2018-03-09 14:31
This is what I got doing that through the browser, like you suggested:

```
{"hashes": ["e82abd7f2c8f8c866141634a1ce10da8ebf3c58b68cb2eaa351345777bb3f67c", "0cbe0ac5a400dfc5bf5504805b8529ba010b2df702558693811ae4aa64202271", "d8c52c5fed4c9e89cc3861d3aff2f69fa3c98ce97066638b13ae43e07b6f72e2", "4c25d7905f913c56a56ac022924e460694a78a42ad6b9030333776bd9f459c61", "aa04bba2e99daed8331ff830756941faf559578ae82bcbf16f227525e33d26f3", "d414c076a9f42643ff8168be3bce6cacc38c587a53825eb74f2271511e782a45", "670747e1278e79acd20b1915c91eef90830850887eafe699ba336e326fb7407d", "a9af47266c70086d9e01105b14bbe5ae69b9b4984a95af605c96a95d8b4f7f97", "232a029b390c1fcb42ceba6e1e2e218127f86c3472ae3cd37a9fcb18101000c5", "18572ed41465fd004756e787af4501fcac413d4974b28972f2d5b8e2f0c01465", "333383a1a84cf8b9a030fb130db0dc6fcfc097e0b05fc508497458c4520051c1", "3b4b7f98c4dda7f5a2e281a2f643de8d4dc02c4d46dcc7e0e7ff81dc79a79d3b", "a2cafab3c949989ecb931937bc2d0de80b65a2f47c65a8baf7ad434ecdd6e4f0", "15af3642e3a0e3092fe9d49c2cfe80b67fc8159750407ddc0aed6b2b63903176", "2f95046f5d4b798a2dbb19957b6d9aa14bab3ffa0488c09adb38f816f7779f2c", "afe5b82351d1b1f2416252461e18e4eedc3b7108388776d1c8912b95bd33a99e", "b9705663d216e428953f5473f36e3f033263437144867eda42c93b3669cfa31c", "bc7e564dc76b78b5957c2bb82ad2bfe6075eabbdae4dd55e1f3acc3cc6442e59", "d180b1b876ad3da9b686f0ddff3319c0d1cd5c679ce4590c9f5dfaeaba805976", "b28e96024b7b05ef99bf8d66985b3652ba1d5762339ac92d1bfef812828b37c5", "5729381ddbad85fb1fe3af82a5d74e5840488574d0491b6e0e26a3ffa49156e6", "5376e6efd59ddd2c683b0cc9ee3d62538154a9317ab275817c3d551371ec0bd5", "40eb1b43b2b4227c16e6715ab0ad37dafbcaf2f729c49a36752a57d2ffa21889", "1c9c7aa16e013f1c6b77711897a9a9cc50cab3062c94b8cc271f8f452c9e640b", "d994e8c709926d3a3387a9d722646a8c307d92fcec1cf3d58dcbb3821ada481b"], "next_page": "RmFsc2U6Q3Q0RkN1a0RDc1lEX3dEQVFkYW9uamdBX3dEX0FQLU1nWW1XallxTWk1Q0xucE9jazVDS21fOEFBUDkwYmFDZ21ZdU1vS0RfQUFEX1haNlBqNXFSbUphUm12OEFBUDl6ZEcyV2tadWFoXzhBQVA5ZGpKNlNqNU9halA4QUFQOXpkRzJia0p5Z2xwdl9BQURfWFp2R3hzdWF4NXpJejhiR3pjbWJ6SjdNek1mSW5zYWJ5TTNOeWN2Sm5zZWN6TV9JbThiTm1aeWFuTTZjbWN5YnlzZWJuSjJkek1mTnpwNmJuc3ZIenAzX0FBRF9jMy1ieHNiTG1zZWN5TV9HeHMzSm04eWV6TXpIeUo3R204ak56Y25MeVo3SG5NelB5SnZHelptY21wek9uSm5NbThySG01eWRuY3pIemM2ZW01N0x4ODZkX3dBQV9fOEFfdl8tXzR5QmlaYU5pb3lMa0l1ZWs1eVRrSXFiX3dCMGJhQ2dtWXVNb0tEX0FGMmVqNC1ha1ppV2tacl9BSE4wYlphUm01cUhfd0Jkako2U2o1T2FqUDhBYzNSdG01Q2NvSmFiX3dCZG04Ykd5NXJIbk1qUHhzYk55WnZNbnN6TXg4aWV4cHZJemMzSnk4bWV4NXpNejhpYnhzMlpuSnFjenB5WnpKdkt4NXVjblozTXg4M09ucHVleThmT25mOEFjMy1ieHNiTG1zZWN5TV9HeHMzSm04eWV6TXpIeUo3R204ak56Y25MeVo3SG5NelB5SnZHelptY21wek9uSm5NbThySG01eWRuY3pIemM2ZW01N0x4ODZkX3dEX19oQVpJZHRlTDlHYkpOVEpVQUJhQ3dsOWdDaEpLYzlaTnhBQ1lKS1Vob0VFRWcxRWIyTjFiV1Z1ZEVsdVpHVjRHbzhCS0VGT1JDQW9TVk1nSW1OMWMzUnZiV1Z5WDI1aGJXVWlJQ0poY0hCbGJtZHBibVVpS1NBb1NWTWdJbWR5YjNWd1gyNWhiV1VpSUNKemZuWnBjblZ6ZEc5MFlXeGpiRzkxWkNJcElDaEpVeUFpYm1GdFpYTndZV05sSWlBaUlpa2dLRWxUSUNKcGJtUmxlRjl1WVcxbElpQWljMkZ0Y0d4bGN5SXBJQ2hGVVNBeElDSnpibUp5WDNSNWNHVWlLU2s2R2dvTktFNGdJbk51WW5KZmJITWlLUkFCR1FBQUFBQUFBQUFBU2hnSUFEb1NZblJwWDJkbGJtVnlhV05mYzJOdmNtVnlRQmxTR1FvTUtFNGdiM0prWlhKZmFXUXBFQUVaQUFBQUFBQUE4UDg=", "result": 1}
```

**Comment by leadZERO** [comment] 2018-03-09 16:43
That's the correct output in the browser so your key is working. 

What happens when you use the get_hashes_from_search('type:peexe') function? 

The other thing I suspect might be the issue is the shear volume that query will pull back. (As you can imagine, VT has quite a few PE files). It might not be the first few queries that are failing but one of the later calls to get_hashes_from_search() with a next_page.

**Comment by keithjjones** [comment] 2018-03-09 16:51
I get the hashes with that function.  As expected.

**Comment by leadZERO** [comment] 2018-03-09 17:04
I wonder if it's hitting that exception after it hits some kind of limit. 

Did you get the same error when you run:
```python3
get_all_file_report_pages('type:peexe AND size:250-')
```

**Comment by keithjjones** [comment] 2018-03-09 17:10
That gives me the error:

```
>>> np, res = ia.get_all_file_report_pages('type:peexe AND size:250-')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/Python3/lib/python3.5/site-packages/virus_total_apis/api.py", line 909, in get_all_file_report_pages
    next_page, response = self.get_hashes_from_search(self, query)
  File "/usr/local/anaconda3/envs/Python3/lib/python3.5/site-packages/virus_total_apis/api.py", line 863, in get_hashes_from_search
    return response.json().get('next_page'), response
  File "/usr/local/anaconda3/envs/Python3/lib/python3.5/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/anaconda3/envs/Python3/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/anaconda3/envs/Python3/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/anaconda3/envs/Python3/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 1 (char 4)
```

**Comment by keithjjones** [comment] 2018-03-09 17:27
Sure.  Excuse the dumb question - but what's the easiest way to get this into a pip installed module?  Find the py and edit it directly?

**Comment by keithjjones** [comment] 2018-03-09 17:27
And I believe intel API and private API count separately.

**Comment by leadZERO** [comment] 2018-03-09 17:38
hmm You could do it that way. The (probably cleaner) way would be to clone the repo and then load that module into python:

```
(py27) 128 ...:~/temp$ git clone git@github.com:blacktop/virustotal-api
Cloning into 'virustotal-api'...
remote: Counting objects: 392, done.
remote: Total 392 (delta 0), reused 0 (delta 0), pack-reused 392
Receiving objects: 100% (392/392), 108.88 KiB | 363.00 KiB/s, done.
Resolving deltas: 100% (218/218), done.
(py27) ...:~/temp$ cd virustotal-api
(py27) ...:~/temp/virustotal-api$ export PYTHONPATH=`pwd`
(py27) ...:~/temp/virustotal-api$ python
Python 2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 11:07:58)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import virus_total_apis
```

**Comment by keithjjones** [comment] 2018-03-09 17:42
I'd have to pip uninstall the installed version for that to work, right?  Right now I have a long process running that is using the installed module.  I might not be able to test this today.

**Comment by leadZERO** [comment] 2018-03-09 17:47
Nope this should work without having to uninstall first. This is how you can work on modules while also having a "working" version installed via PIP. Using the PYTHONPATH environment variable takes precedence.

**Comment by leadZERO** [comment] 2018-03-09 17:49
And I think you don't need to use PYTHONPATH when loading from the current directory... But I typically set it just in case.

**Comment by keithjjones** [comment] 2018-03-09 17:59
Ok, that allows me to test.  There are two typos above, the code should be:

```
    def get_hashes_from_search(self, query, page=None, timeout=None):
        """ Get the scan results for a file.

        Even if you do not have a Private Mass API key that you can use, you can still automate VirusTotal Intelligence
        searches pretty much in the same way that the searching for files api call works.

        :param query: a VirusTotal Intelligence search string in accordance with the file search documentation .
            <https://www.virustotal.com/intelligence/help/file-search/>
        :param page: the next_page property of the results of a previously issued query to this API. This parameter
            should not be provided if it is the very first query to the API, i.e. if we are retrieving the
            first page of results.
        :param timeout: The amount of time in seconds the request should wait before timing out.

        apikey: the API key associated to a VirusTotal Community account with VirusTotal Intelligence privileges.
        """
        params = {'query': query, 'apikey': self.api_key, 'page': page}

        try:
            response = requests.get(self.base + 'search/programmatic/',
                                    params=params,
                                    proxies=self.proxies,
                                    timeout=timeout)
        except requests.RequestException as e:
            return dict(error=str(e))

        if response.url.find('quota-exceeded') >= 0:
            print('Quota Exceeded!')
            raise requests.RequestException()

        return _return_response_and_status_code(response)
```

With that, I get the following error:

```
>>> ia.get_all_file_report_pages('type:peexe AND size:250-')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Source/malgazer/virustotal-api/virus_total_apis/api.py", line 914, in get_all_file_report_pages
    next_page, response = self.get_hashes_from_search(self, query)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by leadZERO** [comment] 2018-03-09 18:04
gah sorry forgot I had modifications in my fork.... Could you use: git clone git@github.com:leadZERO/virustotal-api

**Comment by keithjjones** [comment] 2018-03-09 18:09
master branch?  I'm not seeing the changes in your master branch.

**Comment by leadZERO** [comment] 2018-03-09 18:09
Ok... Make the specified modification to the repo pulled from this command:
```git clone git@github.com:leadZERO/virustotal-api --branch ReturnCleanup```

**Comment by keithjjones** [comment] 2018-03-09 18:10
That works for me.  I get the expected data back.

**Comment by leadZERO** [comment] 2018-03-09 18:11
Which expected data, quota exceeded or the correct results?

**Comment by keithjjones** [comment] 2018-03-09 18:15
Sorry, the hashes.  I didn't get a quota exceeded.

**Comment by leadZERO** [comment] 2018-03-09 18:16
Interesting, doing the "AND size:250-" or the full "type:peexe"?

**Comment by keithjjones** [comment] 2018-03-09 18:19
I did it with the size, which threw the error before, but now dumps a ton of data.  When I run the full "type:peexe" I get less hashes, for some reason.

**Comment by leadZERO** [comment] 2018-03-09 18:27
well, glad it's working none the less... I think something might have been going on with the quota limits. Let me know if you have any more issues, otherwise, I'll reiterate PR#23 .

**Comment by keithjjones** [comment] 2018-03-09 19:02
I think this fixes it.  I think I called the wrong function when I got wrong numbers.  I got too many windows open and doing too much. :)

```
>>> g = ia.get_all_file_report_pages('type:peexe AND size:250-')
>>> len(g['results'])
13
>>> f = ia.get_all_file_report_pages('type:peexe')
...this took foreeeeeeever...
```
I didn't let the last line complete, but it didn't throw an exception after running for a really long time.

Thanks for the quick turnaround!

**Comment by blacktop** [comment] 2018-03-09 23:29
Wow, now THAT's an issue! 😉 

So to summarize #23 fixes this issue?

**Comment by keithjjones** [comment] 2018-03-09 23:42
The last repo you guys said to pull and try fixes the exception issue.

**Comment by keithjjones** [comment] 2018-03-12 15:15
Do you want me to close this now or do you want to tag the fix to this issue?

**Comment by leadZERO** [comment] 2018-03-12 18:18
Yes, #23 will fix this issue. @blacktop feel free to merge it.

**Comment by blacktop** [comment] 2018-03-12 18:25
@leadZERO @keithjjones thank you for this! 👍 sorry for the delay, I have been getting my brain melted in a 4day Dojo at CanSecWest!  I will get this merged in now and pushed to PyPi by the end of the day.

Cheers!

**Closed** 2018-03-12 18:29 UTC
